apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chat-bot
rules:
- apiGroups:
  - site.ddev.live
  resources:
  - siteimagesources
  - siteclones
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - cms.ddev.live
  resources:
  - drupalsites
  - typo3sites
  - wordpresses
  verbs:
  - get
  - list
  - watch
